# Main university terms.
TUEBINGEN_PHRASES = [
    "tübingen",
    "tuebingen",
    "uni tübingen",
    "uni-tuebingen",
    "universität tübingen",
    "university of tübingen",
    "university of tuebingen",
    "eberhard karls universität tübingen",
    "eberhard karls university of tuebingen",
    "eberhard-karls-universität",
    "eberhard-karls-university",
    "eberhard karls",
    "ekut",
    "tuebingen university",
    "tuebingen universität",
    "tuebingen universitaet",
    "univ tübingen",
    "univ tuebingen",
    "tübingen alumni",
    "tuebingen student",
    "tübingen research",
    "tuebingen research",
    "tübingen campus",
    "tuebingen campus",
    "tuebingen library",
    "tübingen library",
    "university hospital tübingen",
    "university hospital tuebingen",
    "medizinische fakultät tübingen",
    "faculty of medicine tübingen",
    "faculty of medicine tuebingen",
    "tuebingen medical center",
    "tuebingen medical faculty",
    "tuebingen neuroscience",
    "tübingen neuroscience",
    "tuebingen cognitive science",
    "tuebingen computer science",
    "tuebingen informatics",
    "tuebingen mathematics",
    "tuebingen physics",
    "tuebingen chemistry",
    "tuebingen law faculty",
    "faculty of law tübingen",
    "tuebingen environmental studies",
    "tuebingen psychology",
    "tuebingen molecular biology",
    "tuebingen international office",
    "tuebingen exchange program",
    "tuebingen erasmus",
    "tuebingen graduate school",
    "graduate school tübingen",
    "tuebingen phd program",
    "phd tübingen",
    "doctoral tübingen",
    "tuebingen master program",
    "masters tübingen",
    "tuebingen bachelors",
    "bachelor tübingen",
    "studying in tübingen",
    "studying in tuebingen",
    "living in tübingen",
    "living in tuebingen"
]

# City, regional, and cultural terms
CITY_TERMS = [
    "stadt tübingen",
    "stadt tuebingen",
    "tübingen city",
    "tuebingen city",
    "tübingen germany",
    "tuebingen germany",
    "baden-württemberg",
    "neckar river",
    "neckarbrücke",
    "alte botanischer garten",
    "botanischer garten tübingen",
    "alten botanischen garten",
    "holzmarkt tübingen",
    "markt tübingen",
    "tübingen altstadt",
    "tuebingen old town",
    "hölderlin tower",
    "holderlinturm",
    "tübinger schloss",
    "tuebingen castle",
    "burg tübingen",
    "schloss tübingen",
    "tuebingen bus",
    "tuebingen hbf",
    "tübingen main station",
    "tuebingen train station",
    "tuebingen zentral",
    "tuebingen regional",
    "tuebingen tourist",
    "tuebingen market square",
    "tuebingen weihnachtsmarkt",
    "tuebingen christmas market",
    "tuebingen museums",
    "tuebingen kunsthalle",
    "tuebingen theater"
]

# University facilities, student life, and international
UNIVERSITY_TERMS = [
    "student council tübingen",
    "asta tübingen",
    "studierendenwerk tübingen",
    "tuebingen international students",
    "international office tübingen",
    "tuebingen welcome center",
    "tuebingen language center",
    "university sports tübingen",
    "tuebingen uni sport",
    "student dorm tübingen",
    "tuebingen studentenwohnheim",
    "student housing tübingen",
    "erasmus tübingen",
    "tuebingen buddy program",
    "tuebingen orientation week",
    "orientation tübingen",
    "academic calendar tübingen",
    "tuebingen summer school",
    "tuebingen winter semester",
    "semesterbeitrag tübingen"
]

# Faculties and research centers
FACULTY_TERMS = [
    "faculty of medicine tübingen",
    "faculty of science tübingen",
    "faculty of law tübingen",
    "faculty of humanities tübingen",
    "faculty of economics tübingen",
    "faculty of social sciences tübingen",
    "faculty of protestant theology tübingen",
    "faculty of catholic theology tübingen",
    "tuebingen max planck institute",
    "tuebingen centre for integrative neuroscience",
    "tuebingen ifi",
    "tuebingen zmbp",
    "tuebingen fraunhofer institute",
    "tuebingen cluster of excellence",
    "cyber valley tübingen",
    "cyber valley tuebingen"
]

# Academic and research context terms
ACADEMIC_TERMS = [
    "research",
    "study",
    "faculty",
    "department",
    "campus",
    "professor",
    "lecture",
    "seminar",
    "workshop",
    "laboratory",
    "lab",
    "institute",
    "center",
    "zentrum",
    "thesis",
    "dissertation",
    "scholarship",
    "enrollment",
    "curriculum",
    "publication",
    "conference",
    "symposium",
    "journal",
    "library",
    "graduation",
    "exchange",
    "phd",
    "master",
    "bachelor",
    "doctoral",
    "student union",
    "international",
    "matriculation",
    "registration",
    "admissions",
    "tuition",
    "tuition fee",
    "credits",
    "internship",
    "mentor",
    "alumni",
    "tutor",
    "staff",
    "university ranking"
]

ALL_TUEBINGEN_TERMS = (
    TUEBINGEN_PHRASES +
    CITY_TERMS +
    UNIVERSITY_TERMS +
    FACULTY_TERMS
)

