# Document Reranker API Configuration

# HuggingFace Model Configuration
huggingface:
  model_name: "sentence-transformers/sentence-t5-base"
# Server Configuration
server:
  host: "0.0.0.0"     # Server host (0.0.0.0 for all interfaces, 127.0.0.1 for localhost only)
  port: 8000          # Server port
  title: "Document Reranker API"
  version: "1.0.0"
  description: "A FastAPI-based web service that reranks text documents based on semantic similarity to a query using sliding window embeddings"

# File Processing Configuration
file_processing:
  supported_extensions: [".txt"]  # Supported file extensions
  encoding: "utf-8"              # File encoding
  max_file_size_mb: 100          # Maximum file size in MB (optional limit)

# Database Configuration
database:
  data_path: "crawlerDb.duckdb"
  # JSON file should contain list of dicts with fields: doc_id, sentence, title, url, text, similarity

# Similarity Calculation
similarity:
  metric: "cosine"  # Similarity metric (cosine, euclidean, etc.)
  batch_size: 32
  smoothing: 0.0 # Smoothing factor for new similarity calculation (0.0 means take only new similarity)
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Cache Settings (for future implementation)
cache:
  enabled: false              # Enable/disable caching
  ttl_seconds: 3600          # Cache time-to-live in seconds
  max_size_mb: 500           # Maximum cache size in MB 
