# -*- coding: utf-8 -*-
"""Seedipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uCzWnwi8VYwrdVjuSHiWNogASo0oLOo
"""

# Seed=["https://uni-tuebingen.de/en/",
#       "https://www.medizin.uni-tuebingen.de/en-de/startseite",
#       "https://www.tuebingen.mpg.de/en",
#       "https://tuebingen.ai/",
#       "https://tuebingenresearchcampus.com/",
#       "https://www.hih-tuebingen.de/en/",
#       "https://www.dzif.de/en/partner-sites/tubingen",
#       "https://cyber-valley.de/en"
#       "https://www.tuebingen.de/",
#       "https://www.swtue.de/en",
#       "https://www.tripadvisor.co.uk/Tourism-g198539-Tubingen_Baden_Wurttemberg-Vacations.html", #include these after the crawler is well developed.
#       "https://www.tuebus.de/en/index.html",
#       "https://en.wikivoyage.org/wiki/T%C3%BCbingen",#include these after the crawler is well developed.
#       "https://www.my-stuwe.de/en/housing/halls-of-residence-tuebingen/",
#       "https://tuenews.de/en/latest-news-english/",#include these after the crawler is well developed.
#       "https://www.thelocal.de/tag/tubingen/", #include these after the crawler is well developed.
#       "https://www.stadtmuseum-tuebingen.de/english/",#stadtmuseum
#       "https://www.dai-tuebingen.de/en/welcome-to-the-german-american-institute-tubingen.html", #German American institute
#       "https://www.my-stuwe.de/en/", #studentenwerk
#       "https://kunsthalle-tuebingen.de/en/current-exhibition/", #Kunsthalle Tuebingen
#       "https://www.kks-netzwerk.de/en/network/about-us/members/translate-to-english-tuebingen/" #KKS-Netwerk
#       "https://www.swtue.de/en/index.html?srsltid=AfmBOopEWoN9QWLnDe-5uRXZioAJRE6_dCYIodBzFpkzjmrvKq-8b02M", #not the Full website of Stadtwerke, only private costumer

#       ]
Seed = ['https://doclandmed.com/en/germany/clinic/university-hospital-of-tubingen',
 'https://www.krone-tuebingen.de/en/',
 'https://www.thelocal.de/tag/tubingen/',
 'https://integreat.app/tuebingen/en/mobility/vehicle-registration-office',
 'https://www.tripadvisor.co.uk/Tourism-g198539-Tubingen_Baden_Wurttemberg-Vacations.html',
 'https://www.my-stuwe.de/en/',
 'https://velvetescape.com/things-to-do-in-tubingen/',
 'https://guidetoeurope.com/germany/destinations/tubingen',
 'https://www.reddit.com/r/Tuebingen/comments/1iscxbg/wo_kann_man_hier_gut_essen/?tl=en',
 'https://www.youtube.com/c/T%C3%BCbingenML',
 'https://www.topuniversities.com/universities/eberhard-karls-universitat-tubingen',
 'https://www.iqair.com/germany/baden-wuerttemberg/tubingen?srsltid=AfmBOop0FexAS1Dh9421to0IAiFqdJBPFaSL7GLuCfZjVYvRTMBOxNyK',
 'https://www.excelsior-bikes.com/en/magazine/one-day-in-tuebingen-discover-sights-cafes-by-bike/',
 'https://en.parkopedia.de/parking/tuebingen/?arriving=202507112000&leaving=202507112200',
 'https://www.outdooractive.com/en/places-to-eat-and-drink/tuebingen/eat-and-drink-in-tuebingen/21873363/',
 'https://www.mygermanuniversity.com/studyfinder?p=1&pp=20&sort=featured&dir=ASC&cty=144',
 'https://www.pizzeria-dagiovanni.de/en/menu',
 'https://www.naldoland.de/en/naldoland/ziel/26/',
 'https://wanderlog.com/list/geoCategory/199488/where-to-eat-best-restaurants-in-tubingen',
 'https://www.lieferando.de/en/order-drinks-tuebingen',
 'https://www.germany.travel/en/cities-culture/tuebingen.html',
 'https://www.excelsior-bikes.com/en/magazine/one-day-in-tuebingen-discover-sights-cafes-by-bike/ ',
 'https://www.leading-medicine-guide.com/en/medical-experts/university-hospital-tubingen-tuebingen',
 'https://www.opentable.com/region/de/baden-wurttemberg/tubingen-restaurants/',
 'https://tuebingenresearchcampus.com/',
 'https://en.wikivoyage.org/wiki/T%C3%BCbingen',
 'https://aqicn.org/city/germany/badenwurttemberg/tubingen/',
 'https://historicgermany.travel/historic-germany/tubingen/',
 'https://www.badurach-tourismus.de/en/poi/detail/tuebingen-71f22a53f0',
 'https://medium.com/german-city-profiles/t%C3%BCbingen-city-of-poets-and-thinkers-d9efb311c1b',
 'https://visit-tubingen.co.uk/history-of-tubingen-from-pre-history-to-the-present/',
 'https://www.fahrschule-123.de/en/driving-school/fahrschule-armbruster/',
 'https://www.ubereats.com/de-en/city/t%C3%BCbingen-bw?srsltid=AfmBOopb8JvaU-6V2WsSWibSd3gGVn9rttu4jadOEg_Xd6QT5KkGEquG',
 'https://www.bahnhof.de/en/tuebingen-hbf',
 'https://www.dw.com/en/stone-age-art-in-germany-tells-of-our-ancestors-creativity/a-69841364',
 'https://airomedical.com/doctors/country=germany/city=tubingen',
 'https://www.youtube.com/@universitaetsstadt-tuebingen',
 'https://rausgegangen.de/en/tubingen/category/food-and-drinks/',
 'https://oi-clean.de/housekeeping-service-in-tubingen/',
 'https://www.europcar.com/en-us/places/car-rental-germany/tuebingen/tuebingen',
 'https://www.summerschoolsineurope.eu/destination/tubingen-international-european-studies-t-ies/',
 'https://www.swabianalb.info/cities/tuebingen#/article/df9223e2-70e5-4ee9-b3f2-cd2355ab8551',
 'https://www.blue-tomato.com/en-GB/shop/tuebingen/?srsltid=AfmBOooZpV6qn2gqHPQ1Kmh-1NIu4bd7smyyh2X-lZ8Ou35uW1N_-11M',
 'https://www.thelabelfinder.com/t%C3%BCbingen/shops/DE/2820860',
 'https://www.kinderhaus-tuebingen.de/english-version/',
 'https://www.onegreenplanet.org/vegan-food/tubingen-the-european-eco-friendly-vegan-dream-city/',
 'https://www.swtue.de/en/index.html?srsltid=AfmBOopEWoN9QWLnDe-5uRXZioAJRE6_dCYIodBzFpkzjmrvKq-8b02M',
 'https://www.stuttgartcitizen.com/lifestyle/tubingen-offers-history-education-old-world-charm/',
 'https://www.fahrschule-123.de/en/driving-schools/tuebingen/#/?d=10',
 'https://www.youtube.com/@internationaleuropeanstudi5433/about',
 'https://mari-tuebingen.de/mari-tuebingen-en/',
 'https://www.tripadvisor.com/Attraction_Review-g198539-d12498209-Reviews-Historische_Altstadt_Tubingen-Tubingen_Baden_Wurttemberg.html',
 'https://www.mylanguageexchange.com/city/Tuebingen__Germany.asp',
 'https://www.swtue.de/en',
 'https://www.iwm-tuebingen.de/www/index.html',
 'https://www.tuebus.de/en/index.html',
 'https://uk.hotels.com/de374521/hotels-tuebingen-germany/',
 'https://www.bongoroots.de/',
 'https://www.sterlingpresser.com/bicycle-station/',
 'https://www.komoot.com/guide/881/hiking-around-landkreis-tuebingen',
 'https://www.kunsthalle-tuebingen.de/en/',
 'https://www.allgemeinmedizin-tuebingen.de/english-information',
 'https://www.myguide.de/en/cities/tuebingen/',
 'https://www.rentalcars.com/en/city/de/tubingen/',
 'https://integreat.app/tuebingen/en/ukraine/childcare-and-school-visit',
 'https://www.neckartalradweg-bw.de/en/poi/detail/marketplace-tuebingen-9f9bf48077',
 'https://bwz.uw.edu.pl/en/university-of-tubingen-summer-language-courses/',
 'https://www.iwm-tuebingen.de/www/en/index.html',
 'https://www.ksk-tuebingen.de/en/home.html?n=true&stref=logo',
 'https://www.ternbicycles.com/en/dealers/301742',
 'https://www.commerzbank.de/filialen/en/T%C3%BCbingen',
 'https://www.expatrio.com/about-germany/eberhard-karls-universitat-tubingen',
 'https://www.orbitz.com/Tuebingen-Hotels.d181220.Travel-Guide-Hotels',
 'https://www.medizin.uni-tuebingen.de/en-de/startseite',
 'https://www.petbacker.com/s/dog-walking/t%C3%BCbingen--baden~w%C3%BCrttemberg--germany',
 'https://veganfamilyadventures.com/15-best-things-to-do-in-tubingen-germany/',
 'https://theculturetrip.com/europe/germany/articles/the-best-day-trips-from-tubingen-germany',
 'https://visit-tubingen.co.uk/category/things-to-do-in-tubingen/',
 'https://www.findmeglutenfree.com/de/tubingen',
 'https://en.climate-data.org/europe/germany/baden-wuerttemberg/tuebingen-22712/',
 'https://weather-and-climate.com/average-monthly-Rainfall-Temperature-Sunshine,tubingen-baden-wurttemberg-de,Germany',
 'https://www.lieferando.de/en/delivery/food/tuebingen-72074',
 'https://guide.michelin.com/en/de/baden-wurttemberg/tbingen/restaurants?sort=distance',
 'https://sit-sis.de/en/language-journeys/leisure-and-cultural-programm',
 'https://en.parkopedia.com/parking/t%C3%BCbingen/?arriving=202507111900&leaving=202507112100',
 'https://www.engelvoelkers.com/de/en/properties/res/sale/real-estate/baden-wuerttemberg/tuebingen',
 'https://www.radparken-tuebingen.de/en/',
 'https://www.hih-tuebingen.de/en/',
 'https://ghg-tuebingen.de/2024/06/05/electoral-program-2024/',
 'https://www.tripadvisor.com/Restaurants-g198539-Tubingen_Baden_Wurttemberg.html',
 'https://mindtrip.ai/attraction/tubingen-baden-wurttemberg/market-square-marktplatz/at-UCkSyNao',
 'https://cityseeker.com/tuebingen-de',
 'https://www.kayak.com/Cheap-Tuebingen-Car-Rentals.33286.cars.ksp',
 'https://www.reddit.com/r/Tuebingen/comments/10mk9fw/how_is_tuebingen/',
 'https://www.getyourguide.com/tubingen-l150729/',
 'https://en.wikipedia.org/wiki/T%C3%BCbingen',
 'https://www.machinelearningforscience.de/en/predicting-future-energy-supply/',
 'https://deutsche.banklocationmaps.com/en/atm/954011-deutsche-atm-schleifmuhleweg-36',
 'https://www.outdooractive.com/en/cycle-routes/tuebingen/cycling-in-tuebingen/1432906/',
 'https://www.komoot.com/guide/3606931/easy-hikes-around-landkreis-tuebingen',
 'https://pickingupthetabb.wordpress.com/2023/11/11/the-university-city-of-tubingen-germany/',
 'https://www.wg-gesucht.de/en/wg-zimmer-in-Tuebingen.127.0.1.0.html',
 'https://www.helpling.de/de_en/cleaner/tuebingen/',
 'https://www.stadtmuseum-tuebingen.de/english/',
 'https://www.finde.in/tuebingen?lang=en',
 'https://www.mdpi.com/2071-1050/12/3/861',
 'https://www.christianchurch-tuebingen.com/',
 'https://www.energate-messenger.com/news/241588/stadtwerke-tuebingen-largest-solar-park-in-the-region-under-construction',
 'https://one-million-places.com/en/germany/tuebingen-tips-top-sights',
 'https://forbetterscience.com/2024/04/17/gardening-goats-and-external-papermills-in-tubingen/',
 'https://vostel.de/en/volunteering/organisations/1641_Bahnhofsmission-Tuebingen',
 'https://www.wheree.com/g21321-Tubingen',
 'https://keydocuments.net/place/tgn/7004426',
 'https://www.petitfute.co.uk/v48133-tubingen/',
 'https://www.tuebingen.de/',
 'https://www.engie-deutschland.de/en/references/energy-saving-contracting-university-hospital-tubingen',
 'https://www.dzif.de/en/partner-sites/tubingen',
 'https://kunsthalle-tuebingen.de/en/current-exhibition/',
 'https://peeces.de/en/blogs/news/tubingen-vintage-store-guide?srsltid=AfmBOoohmbFijqxpIBJ52bgzU0q681bQuffaoR-mbzv2-9w83yEFMftL',
 'https://www.esg-tuebingen.de/churchatsix',
 'https://placesofgermany.de/en/places/tubingen-old-town/',
 'https://www.element-i.de/en/child-care-centres/die-tueftler/',
 'https://www.happycow.net/europe/germany/tubingen/',
 'https://www.cybo.com/DE/t%C3%BCbingen/clothing-stores/',
 'https://www.hws.de/en/locations/hws-tuebingen-tax-consulting-management-consulting',
 'https://erasmusu.com/en/erasmus-tubingen',
 'https://www.the-studio-tuebingen.de/',
 'https://www.energate-messenger.com/news/244852/the-public-utility-stadtwerke-tuebingen-sets-itself-high-targets-for-the-expansion-of-renewables',
 'https://www.dai-tuebingen.de/en/welcome-to-the-german-american-institute-tubingen.html',
 'https://tuenews.de/en/latest-news-english/',
 'https://bookinghealth.com/university-hospital-tuebingen/departments',
 'https://tuebingenresearchcampus.com/en/tuebingen/living-in-tuebingen/mobility/by-bike',
 'https://www.airbnb.com/rooms/1297116546355903149?source_impression_id=p3_1752201611_P3zji2fDyb2L-X28',
 'https://www.tuebingen.mpg.de/en',
 'https://www.wurstkueche.com/en/drinks/',
 'https://cyber-valley.de/en',
 'https://wundertax.de/en/tax-offices/2886_tuebingen/',
 'https://tuebingen.ai/',
 'https://is.mpg.de/en',
 'https://wanderlog.com/plan/lyeoggallhegbmfq',
 'https://www.youtube.com/@unituebingen',
 'https://commons.wikimedia.org/wiki/Category:Shops_in_T%C3%BCbingen',
 'https://www.geschichtswerkstatt-tuebingen.de/en/projects/history-trail-to-national-socialism',
 'https://velomesto.com/en/de-tuebingen-baden-wuerttemberg/shop/',
 'https://www.kks-netzwerk.de/en/network/about-us/members/translate-to-english-tuebingen/',
 'https://uni-tuebingen.de/en/',
 'https://www.trivago.de/en-US/lm/hotels-t%C3%BCbingen-germany?search=200-1452;dr-20250803-20250804 ',
 'https://www.doctena.de/en/general-practitioner-gp/tubingen',
 'https://www.mygermanyvacation.com/best-things-to-do-and-see-in-tubingen-germany/',
 'https://www.jissen.ac.jp/about/library_mate/71_01.html',
 'https://civis.eu/en/discover-civis/the-civis-alliance/eberhard-karls-universitat-tubingen',
 'https://www.eventim.de/en/cityd/tuebingen-328/konzerte-1/?srsltid=AfmBOoqiXN3SEcHQgHTA-jYYRHfwgrM5HzmnNYV7oxTLtVY9Irkjv-X3',
 'https://www.autoforum-tuebingen.com/',
 'https://miz.org/en/musical-life/institutions/music-schools/tuebingen',
 'https://www.bosch-ebike.com/en/dealers/tubingen-98',
 'https://coparking.ch/en/Germany/car-repair-shop/6542',
 'https://www.vhs-tuebingen.de/kurssuche/liste?knr=251-20908&orderby=ort&orderbyasc=1&browse=forward&knradd=251-20945',
 'https://www.iwm-tuebingen.de/www/en/forschung/forschungsbereiche/AG8_Meurers/index.html',
 'https://www.ostrichtrails.com/europe/germany/tubingen-walking-tour/',
 'https://black-academy.org/black-history-month-2025-in-tubingen/',
 'https://tuebingen.city-map.de/00000001',
 'https://eu.dookan.com/blogs/germany/best-indian-grocery-store-in-tubingen-germany?srsltid=AfmBOooOocRPA79EUFvlate3ujWBZHXRlydqNr0Y44wNKb2gIyAR4muO',
 'https://www.daad.de/en/studying-in-germany/universities/all-degree-programmes/detail/eberhard-karls-university-tuebingen-history-w18730/?hec-id=w18730',
 'https://www.my-stuwe.de/en/housing/halls-of-residence-tuebingen/',
 'https://www.alltrails.com/germany/baden-wurttemberg/tubingen',
 'https://restaurantguru.com/Tubingen',
 'https://www.doctolib.de/allgemeinmedizin/tuebingen',
 'https://www.bandsintown.com/c/tuebingen-germany',
 'https://www.bikemap.net/en/l/2820860/',
 'https://www.waterhardness.net/deutschland/baden-wuerttemberg/72070-tuebingen/72072-buehl.html',
 'https://rausgegangen.de/en/tubingen/category/concerts-and-music/',
 'https://students.tufts.edu/group/26/content/1081',
 'https://rausgegangen.de/en/tubingen/category/market/?lat=48.5236164&lng=9.0535531&city=tubingen&geospatial_query_type=CITY',
 'https://www.britannica.com/place/Tubingen-Germany',
 'https://ecstaticdance.org/dance/ecstatic-dance-tubingen/',
 'https://bookinghealth.com/university-hospital-tuebingen/departments/113941-department-of-gynecology--mammology-and-obstetrics.html',
 'https://www.kloster-bebenhausen.de/en']

"""I have noticed that mostly university websites come up for the queries. So, I have included them in abundance.

This is the educational section, Very good detailed websites, link out generoulsy to related sources.
1. University Website(comes up in almost every query)
2. Uni-Klinic
4. Max-Planck
5. Tuebingen AI centre
6. Tuebingen Research Centre
7. Hertie institute
8. German Centre for Infection Research
9. Cyber Valley


Next I wanted to do offical gov websites but they are in german, However there is an option to translate in english, which unforutnately doesn't make a difference in the URL and might make difficulty in crawling them. (Something to look into?)
I'll include them anyway, But These may not classify as english sources:
1. Tuebingen city website.
2. Stadtwerke Tuebingen


Tourism Websites:
The tourism websites are only in german. And the englsih websites might be too much for our crawler. These ones should work if we make it so that the crawler doesn't crawl pages that lead back to the original website. Still might not work.  

1. Trip-advisor.
2. WikiVoyage.  
3.Wikipedia

Transport and Living:
Both of these will work great.
1.  TU Bus
2. Halls of residence
Can't inlcude WGgesucht because its in german

News:
I would like to include a news website but it might have temporary relevance and sometimes other articel not related to tuebingen. Again crawling process might have to filter. Just an option.
1. Tuenews(Initiative of the landkreis)
2. The local.de (English and tuebingen focused.)



"""